// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package inventory

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/stack11/go-exactonline/api"
	"github.com/stack11/go-exactonline/types"
)

// ItemWarehousesEndpoint is responsible for communicating with
// the ItemWarehouses endpoint of the Inventory service.
type ItemWarehousesEndpoint service

// ItemWarehouses:
// Service: Inventory
// Entity: ItemWarehouses
// URL: /api/v1/{division}/inventory/ItemWarehouses
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=InventoryItemWarehouses
type ItemWarehouses struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: A guid that is the unique identifier of the linkage between item and warehouse
	ID *types.GUID `json:"ID,omitempty"`

	// CountingCycle: Indicates the number of days for next cycle count.
	CountingCycle *int `json:"CountingCycle,omitempty"`

	// Created: Creation date
	Created *types.Date `json:"Created,omitempty"`

	// Creator: User ID of creator
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Name of creator
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// CurrentStock: Quantity that is currently in stock, included the stock committed to sales order
	CurrentStock *float64 `json:"CurrentStock,omitempty"`

	// DefaultStorageLocation: This is a default storage location
	DefaultStorageLocation *types.GUID `json:"DefaultStorageLocation,omitempty"`

	// DefaultStorageLocationCode: Default storage location&#39;s code
	DefaultStorageLocationCode *string `json:"DefaultStorageLocationCode,omitempty"`

	// DefaultStorageLocationDescription: Default storage location&#39;s description
	DefaultStorageLocationDescription *string `json:"DefaultStorageLocationDescription,omitempty"`

	// Division: Division code
	Division *int `json:"Division,omitempty"`

	// Item: Item ID
	Item *types.GUID `json:"Item,omitempty"`

	// ItemBarcode: Barcode of item
	ItemBarcode *string `json:"ItemBarcode,omitempty"`

	// ItemCode: Code of item
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription: Description of item
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// ItemEndDate: Together with ItemStartDate this determines if the item is active
	ItemEndDate *types.Date `json:"ItemEndDate,omitempty"`

	// ItemIsFractionAllowedItem: Indicates if fractions (for example 0.35) are allowed for quantities of this item
	ItemIsFractionAllowedItem *bool `json:"ItemIsFractionAllowedItem,omitempty"`

	// ItemIsStockItem: Indicates if this is a stock item
	ItemIsStockItem *bool `json:"ItemIsStockItem,omitempty"`

	// ItemStartDate: Together with ItemEndDate this determines if the item is active
	ItemStartDate *types.Date `json:"ItemStartDate,omitempty"`

	// ItemUnit: The standard unit code of this item
	ItemUnit *string `json:"ItemUnit,omitempty"`

	// ItemUnitDescription: Description of item&#39;s unit
	ItemUnitDescription *string `json:"ItemUnitDescription,omitempty"`

	// MaximumStock: Maximum quantity of items that you want in warehouse
	MaximumStock *float64 `json:"MaximumStock,omitempty"`

	// Modified: Last modified date
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: User ID of modifier
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Name of modifier
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// NextCountingCycle: Indicates the date for next cycle count
	NextCountingCycle *types.Date `json:"NextCountingCycle,omitempty"`

	// OrderPolicy: Order Policy options: 1-Lot for lot, 2-Fixed order quantity, 3-Min / Max, 4-Order
	OrderPolicy *int `json:"OrderPolicy,omitempty"`

	// Period: Period that work together with replenishment in MRP
	Period *int `json:"Period,omitempty"`

	// PlannedStockIn: The quantity still open to be received based on i.e. purchase orders and assembly orders.
	PlannedStockIn *float64 `json:"PlannedStockIn,omitempty"`

	// PlannedStockOut: The quantity still open to be delivered based on i.e. sales orders and assembly orders.
	PlannedStockOut *float64 `json:"PlannedStockOut,omitempty"`

	// PlanningDetailsUrl: URL of the stock planning details of this record
	PlanningDetailsUrl *string `json:"PlanningDetailsUrl,omitempty"`

	// ProjectedStock: The quantity of stock projected given all planned future stock changes
	ProjectedStock *float64 `json:"ProjectedStock,omitempty"`

	// ReorderPoint: Quantity of items as an indication of when you need to reorder more stock for the warehouse
	ReorderPoint *float64 `json:"ReorderPoint,omitempty"`

	// ReorderQuantity: Reorder quantity that work together with replenishment in MRP
	ReorderQuantity *float64 `json:"ReorderQuantity,omitempty"`

	// ReplenishmentType: Replenishment options: 1-Purchase, 2-Assemble, 3-Make, 4-Transfer, 5-No replenishment advice
	ReplenishmentType *int `json:"ReplenishmentType,omitempty"`

	// ReservedStock: The quantity in a back to back order process which is already received from the purchase order, but not yet delivered for the sales order.
	ReservedStock *float64 `json:"ReservedStock,omitempty"`

	// SafetyStock: Minimum quantity of items you must have in stock
	SafetyStock *float64 `json:"SafetyStock,omitempty"`

	// StorageLocationSequenceNumber: Sequence number of the item (Premium Only)
	StorageLocationSequenceNumber *int `json:"StorageLocationSequenceNumber,omitempty"`

	// StorageLocationUrl: URL pointing to details of which storage locations this ItemWarehouse&#39;s stock is located
	StorageLocationUrl *string `json:"StorageLocationUrl,omitempty"`

	// Warehouse: Warehouse ID
	Warehouse *types.GUID `json:"Warehouse,omitempty"`

	// WarehouseCode: Code of warehouse
	WarehouseCode *string `json:"WarehouseCode,omitempty"`

	// WarehouseDescription: Description of warehouse
	WarehouseDescription *string `json:"WarehouseDescription,omitempty"`
}

func (e *ItemWarehouses) GetPrimary() *types.GUID {
	return e.ID
}

func (s *ItemWarehousesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "inventory/ItemWarehouses", method)
}

// List the ItemWarehouses entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ItemWarehousesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*ItemWarehouses, error) {
	var entities []*ItemWarehouses
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/inventory/ItemWarehouses", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the ItemWarehouses entitiy in the provided division.
func (s *ItemWarehousesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*ItemWarehouses, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/inventory/ItemWarehouses", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &ItemWarehouses{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty ItemWarehouses entity
func (s *ItemWarehousesEndpoint) New() *ItemWarehouses {
	return &ItemWarehouses{}
}

// Create the ItemWarehouses entity in the provided division.
func (s *ItemWarehousesEndpoint) Create(ctx context.Context, division int, entity *ItemWarehouses) (*ItemWarehouses, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/inventory/ItemWarehouses", division) // #nosec
	e := &ItemWarehouses{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the ItemWarehouses entity in the provided division.
func (s *ItemWarehousesEndpoint) Update(ctx context.Context, division int, entity *ItemWarehouses) (*ItemWarehouses, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/inventory/ItemWarehouses", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &ItemWarehouses{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the ItemWarehouses entity in the provided division.
func (s *ItemWarehousesEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/inventory/ItemWarehouses", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
