// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package bulk

import (
	"context"
	"encoding/json"

	"github.com/stack11/go-exactonline/api"
	"github.com/stack11/go-exactonline/types"
)

// SalesOrderSalesOrdersEndpoint is responsible for communicating with
// the SalesOrderSalesOrders endpoint of the Bulk service.
type SalesOrderSalesOrdersEndpoint service

// SalesOrderSalesOrders:
// Service: Bulk
// Entity: SalesOrderSalesOrders
// URL: /api/v1/{division}/bulk/SalesOrder/SalesOrders
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=BulkSalesOrderSalesOrders
type SalesOrderSalesOrders struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// OrderID:
	OrderID *types.GUID `json:"OrderID,omitempty"`

	// AmountDC:
	AmountDC *float64 `json:"AmountDC,omitempty"`

	// AmountDiscount:
	AmountDiscount *float64 `json:"AmountDiscount,omitempty"`

	// AmountDiscountExclVat:
	AmountDiscountExclVat *float64 `json:"AmountDiscountExclVat,omitempty"`

	// AmountFC:
	AmountFC *float64 `json:"AmountFC,omitempty"`

	// AmountFCExclVat:
	AmountFCExclVat *float64 `json:"AmountFCExclVat,omitempty"`

	// ApprovalStatus:
	ApprovalStatus *int `json:"ApprovalStatus,omitempty"`

	// ApprovalStatusDescription:
	ApprovalStatusDescription *string `json:"ApprovalStatusDescription,omitempty"`

	// Approved:
	Approved *types.Date `json:"Approved,omitempty"`

	// Approver:
	Approver *types.GUID `json:"Approver,omitempty"`

	// ApproverFullName:
	ApproverFullName *string `json:"ApproverFullName,omitempty"`

	// Created:
	Created *types.Date `json:"Created,omitempty"`

	// Creator:
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName:
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Currency:
	Currency *string `json:"Currency,omitempty"`

	// DeliverTo:
	DeliverTo *types.GUID `json:"DeliverTo,omitempty"`

	// DeliverToContactPerson:
	DeliverToContactPerson *types.GUID `json:"DeliverToContactPerson,omitempty"`

	// DeliverToContactPersonFullName:
	DeliverToContactPersonFullName *string `json:"DeliverToContactPersonFullName,omitempty"`

	// DeliverToName:
	DeliverToName *string `json:"DeliverToName,omitempty"`

	// DeliveryAddress:
	DeliveryAddress *types.GUID `json:"DeliveryAddress,omitempty"`

	// DeliveryDate:
	DeliveryDate *types.Date `json:"DeliveryDate,omitempty"`

	// DeliveryStatus:
	DeliveryStatus *int `json:"DeliveryStatus,omitempty"`

	// DeliveryStatusDescription:
	DeliveryStatusDescription *string `json:"DeliveryStatusDescription,omitempty"`

	// Description:
	Description *string `json:"Description,omitempty"`

	// Discount:
	Discount *float64 `json:"Discount,omitempty"`

	// Division:
	Division *int `json:"Division,omitempty"`

	// Document:
	Document *types.GUID `json:"Document,omitempty"`

	// DocumentNumber:
	DocumentNumber *int `json:"DocumentNumber,omitempty"`

	// DocumentSubject:
	DocumentSubject *string `json:"DocumentSubject,omitempty"`

	// IncotermAddress:
	IncotermAddress *string `json:"IncotermAddress,omitempty"`

	// IncotermCode:
	IncotermCode *string `json:"IncotermCode,omitempty"`

	// IncotermVersion:
	IncotermVersion *int `json:"IncotermVersion,omitempty"`

	// InvoiceStatus:
	InvoiceStatus *int `json:"InvoiceStatus,omitempty"`

	// InvoiceStatusDescription:
	InvoiceStatusDescription *string `json:"InvoiceStatusDescription,omitempty"`

	// InvoiceTo:
	InvoiceTo *types.GUID `json:"InvoiceTo,omitempty"`

	// InvoiceToContactPerson:
	InvoiceToContactPerson *types.GUID `json:"InvoiceToContactPerson,omitempty"`

	// InvoiceToContactPersonFullName:
	InvoiceToContactPersonFullName *string `json:"InvoiceToContactPersonFullName,omitempty"`

	// InvoiceToName:
	InvoiceToName *string `json:"InvoiceToName,omitempty"`

	// Modified:
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier:
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName:
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// OrderDate:
	OrderDate *types.Date `json:"OrderDate,omitempty"`

	// OrderedBy:
	OrderedBy *types.GUID `json:"OrderedBy,omitempty"`

	// OrderedByContactPerson:
	OrderedByContactPerson *types.GUID `json:"OrderedByContactPerson,omitempty"`

	// OrderedByContactPersonFullName:
	OrderedByContactPersonFullName *string `json:"OrderedByContactPersonFullName,omitempty"`

	// OrderedByName:
	OrderedByName *string `json:"OrderedByName,omitempty"`

	// OrderNumber:
	OrderNumber *int `json:"OrderNumber,omitempty"`

	// PaymentCondition:
	PaymentCondition *string `json:"PaymentCondition,omitempty"`

	// PaymentConditionDescription:
	PaymentConditionDescription *string `json:"PaymentConditionDescription,omitempty"`

	// PaymentReference:
	PaymentReference *string `json:"PaymentReference,omitempty"`

	// Remarks:
	Remarks *string `json:"Remarks,omitempty"`

	// SalesChannel:
	SalesChannel *types.GUID `json:"SalesChannel,omitempty"`

	// SalesChannelCode:
	SalesChannelCode *string `json:"SalesChannelCode,omitempty"`

	// SalesChannelDescription:
	SalesChannelDescription *string `json:"SalesChannelDescription,omitempty"`

	// SalesOrderLines:
	SalesOrderLines *json.RawMessage `json:"SalesOrderLines,omitempty"`

	// Salesperson:
	Salesperson *types.GUID `json:"Salesperson,omitempty"`

	// SalespersonFullName:
	SalespersonFullName *string `json:"SalespersonFullName,omitempty"`

	// SelectionCode:
	SelectionCode *types.GUID `json:"SelectionCode,omitempty"`

	// SelectionCodeCode:
	SelectionCodeCode *string `json:"SelectionCodeCode,omitempty"`

	// SelectionCodeDescription:
	SelectionCodeDescription *string `json:"SelectionCodeDescription,omitempty"`

	// ShippingMethod:
	ShippingMethod *types.GUID `json:"ShippingMethod,omitempty"`

	// ShippingMethodDescription:
	ShippingMethodDescription *string `json:"ShippingMethodDescription,omitempty"`

	// Status:
	Status *int `json:"Status,omitempty"`

	// StatusDescription:
	StatusDescription *string `json:"StatusDescription,omitempty"`

	// TaxSchedule:
	TaxSchedule *types.GUID `json:"TaxSchedule,omitempty"`

	// TaxScheduleCode:
	TaxScheduleCode *string `json:"TaxScheduleCode,omitempty"`

	// TaxScheduleDescription:
	TaxScheduleDescription *string `json:"TaxScheduleDescription,omitempty"`

	// WarehouseCode:
	WarehouseCode *string `json:"WarehouseCode,omitempty"`

	// WarehouseDescription:
	WarehouseDescription *string `json:"WarehouseDescription,omitempty"`

	// WarehouseID:
	WarehouseID *types.GUID `json:"WarehouseID,omitempty"`

	// YourRef:
	YourRef *string `json:"YourRef,omitempty"`
}

func (e *SalesOrderSalesOrders) GetPrimary() *types.GUID {
	return e.OrderID
}

func (s *SalesOrderSalesOrdersEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "SalesOrder/SalesOrders", method)
}

// List the SalesOrderSalesOrders entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SalesOrderSalesOrdersEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*SalesOrderSalesOrders, error) {
	var entities []*SalesOrderSalesOrders
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/bulk/SalesOrder/SalesOrders", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the SalesOrderSalesOrders entitiy in the provided division.
func (s *SalesOrderSalesOrdersEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*SalesOrderSalesOrders, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/bulk/SalesOrder/SalesOrders", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &SalesOrderSalesOrders{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
