// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package bulk

import "github.com/stack11/go-exactonline/api"

type service struct {
	client *api.Client
}

// BulkService is responsible for communication with the Bulk
// endpoints of the Exact Online API.
type BulkService struct {
	client *api.Client

	common service // Reuse a single struct instead of allocating one for each service on the heap.

	// Endpoints available under this service
	CashflowPayments              *CashflowPaymentsEndpoint
	CashflowReceivables           *CashflowReceivablesEndpoint
	CRMAccounts                   *CRMAccountsEndpoint
	CRMAddresses                  *CRMAddressesEndpoint
	CRMContacts                   *CRMContactsEndpoint
	CRMQuotationLines             *CRMQuotationLinesEndpoint
	CRMQuotations                 *CRMQuotationsEndpoint
	DocumentsDocumentAttachments  *DocumentsDocumentAttachmentsEndpoint
	DocumentsDocuments            *DocumentsDocumentsEndpoint
	FinancialGLAccounts           *FinancialGLAccountsEndpoint
	FinancialGLClassifications    *FinancialGLClassificationsEndpoint
	FinancialTransactionLines     *FinancialTransactionLinesEndpoint
	LogisticsItems                *LogisticsItemsEndpoint
	LogisticsSalesItemPrices      *LogisticsSalesItemPricesEndpoint
	ProjectProjectWBS             *ProjectProjectWBSEndpoint
	SalesInvoiceSalesInvoiceLines *SalesInvoiceSalesInvoiceLinesEndpoint
	SalesInvoiceSalesInvoices     *SalesInvoiceSalesInvoicesEndpoint
	SalesOrderGoodsDeliveries     *SalesOrderGoodsDeliveriesEndpoint
	SalesOrderGoodsDeliveryLines  *SalesOrderGoodsDeliveryLinesEndpoint
	SalesOrderSalesOrderLines     *SalesOrderSalesOrderLinesEndpoint
	SalesOrderSalesOrders         *SalesOrderSalesOrdersEndpoint
}

// NewBulkService creates a new initialized instance of the
// BulkService.
func NewBulkService(apiClient *api.Client) *BulkService {
	s := &BulkService{client: apiClient}

	s.common.client = apiClient

	s.CashflowPayments = (*CashflowPaymentsEndpoint)(&s.common)
	s.CashflowReceivables = (*CashflowReceivablesEndpoint)(&s.common)
	s.CRMAccounts = (*CRMAccountsEndpoint)(&s.common)
	s.CRMAddresses = (*CRMAddressesEndpoint)(&s.common)
	s.CRMContacts = (*CRMContactsEndpoint)(&s.common)
	s.CRMQuotationLines = (*CRMQuotationLinesEndpoint)(&s.common)
	s.CRMQuotations = (*CRMQuotationsEndpoint)(&s.common)
	s.DocumentsDocumentAttachments = (*DocumentsDocumentAttachmentsEndpoint)(&s.common)
	s.DocumentsDocuments = (*DocumentsDocumentsEndpoint)(&s.common)
	s.FinancialGLAccounts = (*FinancialGLAccountsEndpoint)(&s.common)
	s.FinancialGLClassifications = (*FinancialGLClassificationsEndpoint)(&s.common)
	s.FinancialTransactionLines = (*FinancialTransactionLinesEndpoint)(&s.common)
	s.LogisticsItems = (*LogisticsItemsEndpoint)(&s.common)
	s.LogisticsSalesItemPrices = (*LogisticsSalesItemPricesEndpoint)(&s.common)
	s.ProjectProjectWBS = (*ProjectProjectWBSEndpoint)(&s.common)
	s.SalesInvoiceSalesInvoiceLines = (*SalesInvoiceSalesInvoiceLinesEndpoint)(&s.common)
	s.SalesInvoiceSalesInvoices = (*SalesInvoiceSalesInvoicesEndpoint)(&s.common)
	s.SalesOrderGoodsDeliveries = (*SalesOrderGoodsDeliveriesEndpoint)(&s.common)
	s.SalesOrderGoodsDeliveryLines = (*SalesOrderGoodsDeliveryLinesEndpoint)(&s.common)
	s.SalesOrderSalesOrderLines = (*SalesOrderSalesOrderLinesEndpoint)(&s.common)
	s.SalesOrderSalesOrders = (*SalesOrderSalesOrdersEndpoint)(&s.common)

	return s
}
