// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package subscription

import (
	"context"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/stack11/go-exactonline/api"
	"github.com/stack11/go-exactonline/types"
)

// SubscriptionsEndpoint is responsible for communicating with
// the Subscriptions endpoint of the Subscription service.
type SubscriptionsEndpoint service

// Subscriptions:
// Service: Subscription
// Entity: Subscriptions
// URL: /api/v1/{division}/subscription/Subscriptions
// HasWebhook: true
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SubscriptionSubscriptions
type Subscriptions struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// EntryID:
	EntryID *types.GUID `json:"EntryID,omitempty"`

	// BlockEntry:
	BlockEntry *bool `json:"BlockEntry,omitempty"`

	// CancellationDate:
	CancellationDate *types.Date `json:"CancellationDate,omitempty"`

	// Classification:
	Classification *types.GUID `json:"Classification,omitempty"`

	// ClassificationCode:
	ClassificationCode *string `json:"ClassificationCode,omitempty"`

	// ClassificationDescription:
	ClassificationDescription *string `json:"ClassificationDescription,omitempty"`

	// Created:
	Created *types.Date `json:"Created,omitempty"`

	// Creator:
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName:
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Currency:
	Currency *string `json:"Currency,omitempty"`

	// CustomerPONumber:
	CustomerPONumber *string `json:"CustomerPONumber,omitempty"`

	// Description:
	Description *string `json:"Description,omitempty"`

	// Division:
	Division *int `json:"Division,omitempty"`

	// EndDate:
	EndDate *types.Date `json:"EndDate,omitempty"`

	// InvoiceDay:
	InvoiceDay *byte `json:"InvoiceDay,omitempty"`

	// InvoicedTo:
	InvoicedTo *types.Date `json:"InvoicedTo,omitempty"`

	// InvoiceTo:
	InvoiceTo *types.GUID `json:"InvoiceTo,omitempty"`

	// InvoiceToContactPerson:
	InvoiceToContactPerson *types.GUID `json:"InvoiceToContactPerson,omitempty"`

	// InvoiceToContactPersonFullName:
	InvoiceToContactPersonFullName *string `json:"InvoiceToContactPersonFullName,omitempty"`

	// InvoiceToName:
	InvoiceToName *string `json:"InvoiceToName,omitempty"`

	// InvoicingStartDate:
	InvoicingStartDate *types.Date `json:"InvoicingStartDate,omitempty"`

	// Modified:
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier:
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName:
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes:
	Notes *string `json:"Notes,omitempty"`

	// Number:
	Number *int `json:"Number,omitempty"`

	// OrderedBy:
	OrderedBy *types.GUID `json:"OrderedBy,omitempty"`

	// OrderedByContactPerson:
	OrderedByContactPerson *types.GUID `json:"OrderedByContactPerson,omitempty"`

	// OrderedByContactPersonFullName:
	OrderedByContactPersonFullName *string `json:"OrderedByContactPersonFullName,omitempty"`

	// OrderedByName:
	OrderedByName *string `json:"OrderedByName,omitempty"`

	// PaymentCondition:
	PaymentCondition *string `json:"PaymentCondition,omitempty"`

	// PaymentConditionDescription:
	PaymentConditionDescription *string `json:"PaymentConditionDescription,omitempty"`

	// Printed:
	Printed *bool `json:"Printed,omitempty"`

	// Project:
	Project *types.GUID `json:"Project,omitempty"`

	// ReasonCancelled:
	ReasonCancelled *types.GUID `json:"ReasonCancelled,omitempty"`

	// ReasonCancelledCode:
	ReasonCancelledCode *string `json:"ReasonCancelledCode,omitempty"`

	// ReasonCancelledDescription:
	ReasonCancelledDescription *string `json:"ReasonCancelledDescription,omitempty"`

	// StartDate:
	StartDate *types.Date `json:"StartDate,omitempty"`

	// SubscriptionLines:
	SubscriptionLines *json.RawMessage `json:"SubscriptionLines,omitempty"`

	// SubscriptionRestrictionEmployees:
	SubscriptionRestrictionEmployees *json.RawMessage `json:"SubscriptionRestrictionEmployees,omitempty"`

	// SubscriptionRestrictionItems:
	SubscriptionRestrictionItems *json.RawMessage `json:"SubscriptionRestrictionItems,omitempty"`

	// SubscriptionType:
	SubscriptionType *types.GUID `json:"SubscriptionType,omitempty"`

	// SubscriptionTypeCode:
	SubscriptionTypeCode *string `json:"SubscriptionTypeCode,omitempty"`

	// SubscriptionTypeDescription:
	SubscriptionTypeDescription *string `json:"SubscriptionTypeDescription,omitempty"`
}

func (e *Subscriptions) GetPrimary() *types.GUID {
	return e.EntryID
}

func (s *SubscriptionsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "subscription/Subscriptions", method)
}

// List the Subscriptions entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SubscriptionsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*Subscriptions, error) {
	var entities []*Subscriptions
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/subscription/Subscriptions", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the Subscriptions entitiy in the provided division.
func (s *SubscriptionsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*Subscriptions, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/subscription/Subscriptions", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &Subscriptions{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty Subscriptions entity
func (s *SubscriptionsEndpoint) New() *Subscriptions {
	return &Subscriptions{}
}

// Create the Subscriptions entity in the provided division.
func (s *SubscriptionsEndpoint) Create(ctx context.Context, division int, entity *Subscriptions) (*Subscriptions, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/subscription/Subscriptions", division) // #nosec
	e := &Subscriptions{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the Subscriptions entity in the provided division.
func (s *SubscriptionsEndpoint) Update(ctx context.Context, division int, entity *Subscriptions) (*Subscriptions, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/subscription/Subscriptions", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &Subscriptions{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the Subscriptions entity in the provided division.
func (s *SubscriptionsEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/subscription/Subscriptions", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
