// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package subscription

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/stack11/go-exactonline/api"
	"github.com/stack11/go-exactonline/types"
)

// SubscriptionLinesEndpoint is responsible for communicating with
// the SubscriptionLines endpoint of the Subscription service.
type SubscriptionLinesEndpoint service

// SubscriptionLines:
// Service: Subscription
// Entity: SubscriptionLines
// URL: /api/v1/{division}/subscription/SubscriptionLines
// HasWebhook: true
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SubscriptionSubscriptionLines
type SubscriptionLines struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID:
	ID *types.GUID `json:"ID,omitempty"`

	// AmountDC:
	AmountDC *float64 `json:"AmountDC,omitempty"`

	// AmountFC:
	AmountFC *float64 `json:"AmountFC,omitempty"`

	// Costcenter:
	Costcenter *string `json:"Costcenter,omitempty"`

	// Costunit:
	Costunit *string `json:"Costunit,omitempty"`

	// CustomField:
	CustomField *string `json:"CustomField,omitempty"`

	// Description:
	Description *string `json:"Description,omitempty"`

	// Discount:
	Discount *float64 `json:"Discount,omitempty"`

	// Division:
	Division *int `json:"Division,omitempty"`

	// EntryID:
	EntryID *types.GUID `json:"EntryID,omitempty"`

	// FromDate:
	FromDate *types.Date `json:"FromDate,omitempty"`

	// Item:
	Item *types.GUID `json:"Item,omitempty"`

	// ItemDescription:
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// LineNumber:
	LineNumber *int `json:"LineNumber,omitempty"`

	// LineType:
	LineType *int `json:"LineType,omitempty"`

	// LineTypeDescription:
	LineTypeDescription *string `json:"LineTypeDescription,omitempty"`

	// Modified:
	Modified *types.Date `json:"Modified,omitempty"`

	// NetPrice:
	NetPrice *float64 `json:"NetPrice,omitempty"`

	// Notes:
	Notes *string `json:"Notes,omitempty"`

	// Quantity:
	Quantity *float64 `json:"Quantity,omitempty"`

	// SubscriptionNumber:
	SubscriptionNumber *int `json:"SubscriptionNumber,omitempty"`

	// ToDate:
	ToDate *types.Date `json:"ToDate,omitempty"`

	// UnitCode:
	UnitCode *string `json:"UnitCode,omitempty"`

	// UnitDescription:
	UnitDescription *string `json:"UnitDescription,omitempty"`

	// UnitPrice:
	UnitPrice *float64 `json:"UnitPrice,omitempty"`

	// VATAmountFC:
	VATAmountFC *float64 `json:"VATAmountFC,omitempty"`

	// VATCode:
	VATCode *string `json:"VATCode,omitempty"`

	// VATCodeDescription:
	VATCodeDescription *string `json:"VATCodeDescription,omitempty"`
}

func (e *SubscriptionLines) GetPrimary() *types.GUID {
	return e.ID
}

func (s *SubscriptionLinesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "subscription/SubscriptionLines", method)
}

// List the SubscriptionLines entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SubscriptionLinesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*SubscriptionLines, error) {
	var entities []*SubscriptionLines
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/subscription/SubscriptionLines", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the SubscriptionLines entitiy in the provided division.
func (s *SubscriptionLinesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*SubscriptionLines, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/subscription/SubscriptionLines", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &SubscriptionLines{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty SubscriptionLines entity
func (s *SubscriptionLinesEndpoint) New() *SubscriptionLines {
	return &SubscriptionLines{}
}

// Create the SubscriptionLines entity in the provided division.
func (s *SubscriptionLinesEndpoint) Create(ctx context.Context, division int, entity *SubscriptionLines) (*SubscriptionLines, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/subscription/SubscriptionLines", division) // #nosec
	e := &SubscriptionLines{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the SubscriptionLines entity in the provided division.
func (s *SubscriptionLinesEndpoint) Update(ctx context.Context, division int, entity *SubscriptionLines) (*SubscriptionLines, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/subscription/SubscriptionLines", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &SubscriptionLines{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the SubscriptionLines entity in the provided division.
func (s *SubscriptionLinesEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/subscription/SubscriptionLines", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
