// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package sync

import (
	"context"

	"github.com/stack11/go-exactonline/api"
	"github.com/stack11/go-exactonline/types"
)

// InventoryItemWarehousesEndpoint is responsible for communicating with
// the InventoryItemWarehouses endpoint of the Sync service.
type InventoryItemWarehousesEndpoint service

// InventoryItemWarehouses:
// Service: Sync
// Entity: InventoryItemWarehouses
// URL: /api/v1/{division}/sync/Inventory/ItemWarehouses
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SyncInventoryItemWarehouses
type InventoryItemWarehouses struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// Timestamp: Timestamp
	Timestamp *int64 `json:"Timestamp,omitempty"`

	// Created: Creation date
	Created *types.Date `json:"Created,omitempty"`

	// Creator: User ID of creator
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Name of creator
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// DefaultStorageLocation: This is a default storage location
	DefaultStorageLocation *types.GUID `json:"DefaultStorageLocation,omitempty"`

	// DefaultStorageLocationCode: Default storage location&#39;s code
	DefaultStorageLocationCode *string `json:"DefaultStorageLocationCode,omitempty"`

	// DefaultStorageLocationDescription: Default storage location&#39;s description
	DefaultStorageLocationDescription *string `json:"DefaultStorageLocationDescription,omitempty"`

	// Division: Division code
	Division *int `json:"Division,omitempty"`

	// ID: A guid that is the unique identifier of the linkage between item and warehouse
	ID *types.GUID `json:"ID,omitempty"`

	// Item: Item ID
	Item *types.GUID `json:"Item,omitempty"`

	// ItemCode: Code of item
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription: Description of item
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// MaximumStock: Maximum quantity of items that you want in warehouse
	MaximumStock *float64 `json:"MaximumStock,omitempty"`

	// Modified: Last modified date
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: User ID of modifier
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Name of modifier
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// OrderPolicy: Order Policy options: 1-Lot for lot, 2-Fixed order quantity, 3-Min / Max, 4-Order
	OrderPolicy *int `json:"OrderPolicy,omitempty"`

	// Period: Period that work together with replenishment in MRP
	Period *int `json:"Period,omitempty"`

	// ReorderPoint: Quantity of items as an indication of when you need to reorder more stock for the warehouse
	ReorderPoint *float64 `json:"ReorderPoint,omitempty"`

	// ReorderQuantity: Reorder quantity that work together with replenishment in MRP
	ReorderQuantity *float64 `json:"ReorderQuantity,omitempty"`

	// ReplenishmentType: Replenishment options: 1-Purchase, 2-Assemble, 3-Make, 4-Transfer, 5-No replenishment advice
	ReplenishmentType *int `json:"ReplenishmentType,omitempty"`

	// ReservedStock: The quantity in a back to back order process which is already received from the purchase order, but not yet delivered for the sales order.
	ReservedStock *float64 `json:"ReservedStock,omitempty"`

	// SafetyStock: Minimum quantity of items you must have in stock
	SafetyStock *float64 `json:"SafetyStock,omitempty"`

	// Warehouse: Warehouse ID
	Warehouse *types.GUID `json:"Warehouse,omitempty"`

	// WarehouseCode: Code of warehouse
	WarehouseCode *string `json:"WarehouseCode,omitempty"`

	// WarehouseDescription: Description of warehouse
	WarehouseDescription *string `json:"WarehouseDescription,omitempty"`
}

func (e *InventoryItemWarehouses) GetPrimary() *int64 {
	return e.Timestamp
}

func (s *InventoryItemWarehousesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "Inventory/ItemWarehouses", method)
}

// List the InventoryItemWarehouses entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *InventoryItemWarehousesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*InventoryItemWarehouses, error) {
	var entities []*InventoryItemWarehouses
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Inventory/ItemWarehouses", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the InventoryItemWarehouses entitiy in the provided division.
func (s *InventoryItemWarehousesEndpoint) Get(ctx context.Context, division int, id *int64) (*InventoryItemWarehouses, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Inventory/ItemWarehouses", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &InventoryItemWarehouses{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
