// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package sync

import (
	"context"

	"github.com/stack11/go-exactonline/api"
	"github.com/stack11/go-exactonline/types"
)

// ManufacturingShopOrderMaterialPlansEndpoint is responsible for communicating with
// the ManufacturingShopOrderMaterialPlans endpoint of the Sync service.
type ManufacturingShopOrderMaterialPlansEndpoint service

// ManufacturingShopOrderMaterialPlans:
// Service: Sync
// Entity: ManufacturingShopOrderMaterialPlans
// URL: /api/v1/{division}/sync/Manufacturing/ShopOrderMaterialPlans
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SyncManufacturingShopOrderMaterialPlans
type ManufacturingShopOrderMaterialPlans struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// Timestamp: Timestamp
	Timestamp *int64 `json:"Timestamp,omitempty"`

	// Backflush: Indicates if this is a backflush step
	Backflush *byte `json:"Backflush,omitempty"`

	// CalculatorType: Calculator type
	CalculatorType *int `json:"CalculatorType,omitempty"`

	// Created: Creation date
	Created *types.Date `json:"Created,omitempty"`

	// Creator: User ID of creator
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Name of creator
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Description of the material
	Description *string `json:"Description,omitempty"`

	// DetailDrawing: Detail drawing reference
	DetailDrawing *string `json:"DetailDrawing,omitempty"`

	// Division: Division code
	Division *int `json:"Division,omitempty"`

	// ID: Primary key
	ID *types.GUID `json:"ID,omitempty"`

	// Item: Reference to Items table
	Item *types.GUID `json:"Item,omitempty"`

	// ItemCode: Item Code (material)
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription: Description of Item (material)
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// ItemMaterial: Reference to BillOfMaterialMaterials
	ItemMaterial *types.GUID `json:"ItemMaterial,omitempty"`

	// ItemPictureUrl: URL of the material item&#39;s picture
	ItemPictureUrl *string `json:"ItemPictureUrl,omitempty"`

	// LineNumber: Line number
	LineNumber *int `json:"LineNumber,omitempty"`

	// Modified: Last modified date
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: User ID of modifier
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Name of modifier
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Line notes
	Notes *string `json:"Notes,omitempty"`

	// PlannedAmountFC: Planned amount in the currency of the transaction
	PlannedAmountFC *float64 `json:"PlannedAmountFC,omitempty"`

	// PlannedDate: Date that the material is required.
	PlannedDate *types.Date `json:"PlannedDate,omitempty"`

	// PlannedPriceFC: Planned price of the material
	PlannedPriceFC *float64 `json:"PlannedPriceFC,omitempty"`

	// PlannedQuantity: Intended total planned quantity of the material including waste
	PlannedQuantity *float64 `json:"PlannedQuantity,omitempty"`

	// PlannedQuantityFactor: Intended quantity of the material per unit excluding waste
	PlannedQuantityFactor *float64 `json:"PlannedQuantityFactor,omitempty"`

	// RoutingStepID: ID of the routing step.
	RoutingStepID *types.GUID `json:"RoutingStepID,omitempty"`

	// ShopOrder: Reference to ShopOrders table
	ShopOrder *types.GUID `json:"ShopOrder,omitempty"`

	// Status: Line status
	Status *int `json:"Status,omitempty"`

	// StatusDescription: Description of Status
	StatusDescription *string `json:"StatusDescription,omitempty"`

	// Type: Type
	Type *int `json:"Type,omitempty"`

	// Unit: Unit
	Unit *string `json:"Unit,omitempty"`

	// UnitDescription: Unit description
	UnitDescription *string `json:"UnitDescription,omitempty"`

	// WastePercentage: Waste percentage must be null or integer from 1 to 9999 (only available in Manufacturing Professional and Premium)
	WastePercentage *float64 `json:"WastePercentage,omitempty"`
}

func (e *ManufacturingShopOrderMaterialPlans) GetPrimary() *int64 {
	return e.Timestamp
}

func (s *ManufacturingShopOrderMaterialPlansEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "Manufacturing/ShopOrderMaterialPlans", method)
}

// List the ManufacturingShopOrderMaterialPlans entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ManufacturingShopOrderMaterialPlansEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*ManufacturingShopOrderMaterialPlans, error) {
	var entities []*ManufacturingShopOrderMaterialPlans
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Manufacturing/ShopOrderMaterialPlans", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the ManufacturingShopOrderMaterialPlans entitiy in the provided division.
func (s *ManufacturingShopOrderMaterialPlansEndpoint) Get(ctx context.Context, division int, id *int64) (*ManufacturingShopOrderMaterialPlans, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Manufacturing/ShopOrderMaterialPlans", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &ManufacturingShopOrderMaterialPlans{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
