// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package financial

import (
	"context"

	"github.com/stack11/go-exactonline/api"
)

// GLTransactionSourcesEndpoint is responsible for communicating with
// the GLTransactionSources endpoint of the Financial service.
type GLTransactionSourcesEndpoint service

// GLTransactionSources:
// Service: Financial
// Entity: GLTransactionSources
// URL: /api/v1/{division}/financial/GLTransactionSources
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=FinancialGLTransactionSources
type GLTransactionSources struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID:
	ID *int `json:"ID,omitempty"`

	// Description: Find more information here
	Description *string `json:"Description,omitempty"`

	// DescriptionSuffix: Find more information here
	DescriptionSuffix *string `json:"DescriptionSuffix,omitempty"`
}

func (e *GLTransactionSources) GetPrimary() *int {
	return e.ID
}

func (s *GLTransactionSourcesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "financial/GLTransactionSources", method)
}

// List the GLTransactionSources entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *GLTransactionSourcesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*GLTransactionSources, error) {
	var entities []*GLTransactionSources
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/financial/GLTransactionSources", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the GLTransactionSources entitiy in the provided division.
func (s *GLTransactionSourcesEndpoint) Get(ctx context.Context, division int, id *int) (*GLTransactionSources, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/financial/GLTransactionSources", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &GLTransactionSources{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
