// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package financial

import (
	"context"
	"encoding/json"

	"github.com/stack11/go-exactonline/api"
	"github.com/stack11/go-exactonline/types"
)

// ReceivablesListByAccountAndAgeGroupEndpoint is responsible for communicating with
// the ReceivablesListByAccountAndAgeGroup endpoint of the Financial service.
type ReceivablesListByAccountAndAgeGroupEndpoint service

// ReceivablesListByAccountAndAgeGroup:
// Service: Financial
// Entity: ReceivablesListByAccountAndAgeGroup
// URL: /api/v1/{division}/read/financial/ReceivablesListByAccountAndAgeGroup
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ReadFinancialReceivablesListByAccountAndAgeGroup
type ReceivablesListByAccountAndAgeGroup struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// HID: Primary key, human readable ID
	HID *int64 `json:"HID,omitempty"`

	// AccountCode: Code of Account
	AccountCode *string `json:"AccountCode,omitempty"`

	// AccountId: Reference to the account
	AccountId *types.GUID `json:"AccountId,omitempty"`

	// AccountName: Name of Account
	AccountName *string `json:"AccountName,omitempty"`

	// Amount: Amount
	Amount *float64 `json:"Amount,omitempty"`

	// AmountInTransit: Amount in transit - The amount that you have requested your bank to pay
	AmountInTransit *float64 `json:"AmountInTransit,omitempty"`

	// CurrencyCode: Code of Currency
	CurrencyCode *string `json:"CurrencyCode,omitempty"`

	// Description: Description
	Description *string `json:"Description,omitempty"`

	// DueDate: Date the invoice is due (This due date is not the discount due date)
	DueDate *types.Date `json:"DueDate,omitempty"`

	// EntryNumber: The entry number of this payment term corresponding sales/cashflow entry
	EntryNumber *int `json:"EntryNumber,omitempty"`

	// Id: Obsolete
	Id *types.GUID `json:"Id,omitempty"`

	// InvoiceDate: The date of the invoice or the date when money is collected from the customer
	InvoiceDate *types.Date `json:"InvoiceDate,omitempty"`

	// InvoiceNumber: For sales entry, it would be the entrynumber. For the cashflow entry, it will be entrynumber of an invoice which this collection is for
	InvoiceNumber *int `json:"InvoiceNumber,omitempty"`

	// JournalCode: Code of Journal
	JournalCode *string `json:"JournalCode,omitempty"`

	// JournalDescription: Description of Journal
	JournalDescription *string `json:"JournalDescription,omitempty"`

	// Notes: Notes collection
	Notes *json.RawMessage `json:"Notes,omitempty"`

	// YourRef: Sales invoice Your Reference number. Will be null if it is a cashflow entry
	YourRef *string `json:"YourRef,omitempty"`
}

func (e *ReceivablesListByAccountAndAgeGroup) GetPrimary() *int64 {
	return e.HID
}

func (s *ReceivablesListByAccountAndAgeGroupEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "financial/ReceivablesListByAccountAndAgeGroup", method)
}

// List the ReceivablesListByAccountAndAgeGroup entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ReceivablesListByAccountAndAgeGroupEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*ReceivablesListByAccountAndAgeGroup, error) {
	var entities []*ReceivablesListByAccountAndAgeGroup
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/read/financial/ReceivablesListByAccountAndAgeGroup", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the ReceivablesListByAccountAndAgeGroup entitiy in the provided division.
func (s *ReceivablesListByAccountAndAgeGroupEndpoint) Get(ctx context.Context, division int, id *int64) (*ReceivablesListByAccountAndAgeGroup, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/read/financial/ReceivablesListByAccountAndAgeGroup", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &ReceivablesListByAccountAndAgeGroup{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
