// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package salesinvoice

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/stack11/go-exactonline/api"
	"github.com/stack11/go-exactonline/types"
)

// SalesInvoiceOrderChargeLinesEndpoint is responsible for communicating with
// the SalesInvoiceOrderChargeLines endpoint of the SalesInvoice service.
type SalesInvoiceOrderChargeLinesEndpoint service

// SalesInvoiceOrderChargeLines:
// Service: SalesInvoice
// Entity: SalesInvoiceOrderChargeLines
// URL: /api/v1/{division}/salesinvoice/SalesInvoiceOrderChargeLines
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesInvoiceSalesInvoiceOrderChargeLines
type SalesInvoiceOrderChargeLines struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Line ID of shipping method or order charges
	ID *types.GUID `json:"ID,omitempty"`

	// AmountDC: Amount excluded VAT in reporting currency for shipping cost or order charges
	AmountDC *float64 `json:"AmountDC,omitempty"`

	// AmountFCExclVAT: Amount excluded VAT in trading currency for shipping cost or order charges
	AmountFCExclVAT *float64 `json:"AmountFCExclVAT,omitempty"`

	// AmountFCInclVAT: Amount included VAT in trading currency for shipping cost or order charges
	AmountFCInclVAT *float64 `json:"AmountFCInclVAT,omitempty"`

	// AmountVATFC: VAT amount in trading currency for shipping cost or order charges
	AmountVATFC *float64 `json:"AmountVATFC,omitempty"`

	// Division: Division code
	Division *int `json:"Division,omitempty"`

	// GLAccount: The GL Account of the sales invoice order charge line. This field is mandatory. This field is set based on the order charge master
	GLAccount *types.GUID `json:"GLAccount,omitempty"`

	// GLAccountCode: GL account code of shipping cost or order charges
	GLAccountCode *string `json:"GLAccountCode,omitempty"`

	// GLAccountDescription: GL account description of shipping cost or order charges
	GLAccountDescription *string `json:"GLAccountDescription,omitempty"`

	// InvoiceID: The InvoiceID identifies the sales invoice. All the lines of a sales invoice have the same InvoiceID
	InvoiceID *types.GUID `json:"InvoiceID,omitempty"`

	// IsShippingCost: Indicates whether the order charge line is shipping cost
	IsShippingCost *bool `json:"IsShippingCost,omitempty"`

	// LineNumber: Line number of shipping cost and order charges
	LineNumber *int `json:"LineNumber,omitempty"`

	// OrderCharge: ID of order charges is mandatory for order charge. However, it is not required for shipping cost
	OrderCharge *types.GUID `json:"OrderCharge,omitempty"`

	// OrderChargeCode: Code of shipping method or order charges
	OrderChargeCode *string `json:"OrderChargeCode,omitempty"`

	// OrderChargeDescription: Description from shipping method or order charges master
	OrderChargeDescription *string `json:"OrderChargeDescription,omitempty"`

	// OrderChargesLineDescription: Line description of shipping cost or order charges (only available in WD Premium packages)
	OrderChargesLineDescription *string `json:"OrderChargesLineDescription,omitempty"`

	// VATCode: VAT code that is used for shipping cost or order charges
	VATCode *string `json:"VATCode,omitempty"`

	// VATDescription: VAT description for shipping cost or order charges
	VATDescription *string `json:"VATDescription,omitempty"`

	// VATPercentage: The vat percentage of the VAT code. This is the percentage at the moment the invoice is created. It&#39;s also used for the default calculation of VAT amounts and VAT base amounts
	VATPercentage *float64 `json:"VATPercentage,omitempty"`
}

func (e *SalesInvoiceOrderChargeLines) GetPrimary() *types.GUID {
	return e.ID
}

func (s *SalesInvoiceOrderChargeLinesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "salesinvoice/SalesInvoiceOrderChargeLines", method)
}

// List the SalesInvoiceOrderChargeLines entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SalesInvoiceOrderChargeLinesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*SalesInvoiceOrderChargeLines, error) {
	var entities []*SalesInvoiceOrderChargeLines
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesinvoice/SalesInvoiceOrderChargeLines", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the SalesInvoiceOrderChargeLines entitiy in the provided division.
func (s *SalesInvoiceOrderChargeLinesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*SalesInvoiceOrderChargeLines, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesinvoice/SalesInvoiceOrderChargeLines", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &SalesInvoiceOrderChargeLines{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty SalesInvoiceOrderChargeLines entity
func (s *SalesInvoiceOrderChargeLinesEndpoint) New() *SalesInvoiceOrderChargeLines {
	return &SalesInvoiceOrderChargeLines{}
}

// Create the SalesInvoiceOrderChargeLines entity in the provided division.
func (s *SalesInvoiceOrderChargeLinesEndpoint) Create(ctx context.Context, division int, entity *SalesInvoiceOrderChargeLines) (*SalesInvoiceOrderChargeLines, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesinvoice/SalesInvoiceOrderChargeLines", division) // #nosec
	e := &SalesInvoiceOrderChargeLines{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the SalesInvoiceOrderChargeLines entity in the provided division.
func (s *SalesInvoiceOrderChargeLinesEndpoint) Update(ctx context.Context, division int, entity *SalesInvoiceOrderChargeLines) (*SalesInvoiceOrderChargeLines, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesinvoice/SalesInvoiceOrderChargeLines", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &SalesInvoiceOrderChargeLines{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the SalesInvoiceOrderChargeLines entity in the provided division.
func (s *SalesInvoiceOrderChargeLinesEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesinvoice/SalesInvoiceOrderChargeLines", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
