// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package logistics

import (
	"context"

	"github.com/stack11/go-exactonline/api"
	"github.com/stack11/go-exactonline/types"
)

// ItemChargeRelationEndpoint is responsible for communicating with
// the ItemChargeRelation endpoint of the Logistics service.
type ItemChargeRelationEndpoint service

// ItemChargeRelation:
// Service: Logistics
// Entity: ItemChargeRelation
// URL: /api/v1/{division}/logistics/ItemChargeRelation
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=LogisticsItemChargeRelation
type ItemChargeRelation struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Primary key of relationship between item and item charge
	ID *types.GUID `json:"ID,omitempty"`

	// Amount: Item charge amount per unit
	Amount *float64 `json:"Amount,omitempty"`

	// ChargeCode: Code of item charge
	ChargeCode *string `json:"ChargeCode,omitempty"`

	// ChargeDescription: Description of item charge
	ChargeDescription *string `json:"ChargeDescription,omitempty"`

	// ChargeID: Item charge ID
	ChargeID *types.GUID `json:"ChargeID,omitempty"`

	// ChargeVATCode: VAT code that is used when the item charge is registered
	ChargeVATCode *string `json:"ChargeVATCode,omitempty"`

	// ChargeVATDescription: Description of VAT Code
	ChargeVATDescription *string `json:"ChargeVATDescription,omitempty"`

	// ChargeVATPercentage: VAT percentage of the VAT code
	ChargeVATPercentage *float64 `json:"ChargeVATPercentage,omitempty"`

	// ChargeVATType: Indicates how the VAT amount should be calculated in relation to the item charge amount.  // 			B = VAT 0% (Only base amount), E = Excluding, I = Including, N = No VAT
	ChargeVATType *string `json:"ChargeVATType,omitempty"`

	// Created: Creation date
	Created *types.Date `json:"Created,omitempty"`

	// Creator: User ID of creator
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Name of creator
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Currency: Currency of the item charge
	Currency *string `json:"Currency,omitempty"`

	// Division: Division code
	Division *int `json:"Division,omitempty"`

	// ItemCode: Code of item
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription: Description of item
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// ItemID: Item ID
	ItemID *types.GUID `json:"ItemID,omitempty"`

	// Modified: Last modified date
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: User ID of modifier
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Name of modifier
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Quantity: Quantity of the item charge requires in the item
	Quantity *float64 `json:"Quantity,omitempty"`

	// TotalAmount: Total of item charge amount per unit x quantity
	TotalAmount *float64 `json:"TotalAmount,omitempty"`
}

func (e *ItemChargeRelation) GetPrimary() *types.GUID {
	return e.ID
}

func (s *ItemChargeRelationEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "logistics/ItemChargeRelation", method)
}

// List the ItemChargeRelation entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ItemChargeRelationEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*ItemChargeRelation, error) {
	var entities []*ItemChargeRelation
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/logistics/ItemChargeRelation", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the ItemChargeRelation entitiy in the provided division.
func (s *ItemChargeRelationEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*ItemChargeRelation, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/logistics/ItemChargeRelation", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &ItemChargeRelation{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
