// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package crm

import (
	"context"

	"github.com/stack11/go-exactonline/api"
	"github.com/stack11/go-exactonline/types"
)

// LeadPurposesEndpoint is responsible for communicating with
// the LeadPurposes endpoint of the CRM service.
type LeadPurposesEndpoint service

// LeadPurposes:
// Service: CRM
// Entity: LeadPurposes
// URL: /api/v1/{division}/crm/LeadPurposes
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=CRMLeadPurposes
type LeadPurposes struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID:
	ID *types.GUID `json:"ID,omitempty"`

	// Code: Code
	Code *string `json:"Code,omitempty"`

	// Description: Description
	Description *string `json:"Description,omitempty"`
}

func (e *LeadPurposes) GetPrimary() *types.GUID {
	return e.ID
}

func (s *LeadPurposesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "crm/LeadPurposes", method)
}

// List the LeadPurposes entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *LeadPurposesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*LeadPurposes, error) {
	var entities []*LeadPurposes
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/crm/LeadPurposes", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the LeadPurposes entitiy in the provided division.
func (s *LeadPurposesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*LeadPurposes, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/crm/LeadPurposes", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &LeadPurposes{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
