// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package project

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/stack11/go-exactonline/api"
	"github.com/stack11/go-exactonline/types"
)

// ProjectClassificationsEndpoint is responsible for communicating with
// the ProjectClassifications endpoint of the Project service.
type ProjectClassificationsEndpoint service

// ProjectClassifications:
// Service: Project
// Entity: ProjectClassifications
// URL: /api/v1/{division}/project/ProjectClassifications
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ProjectProjectClassifications
type ProjectClassifications struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Primary key
	ID *types.GUID `json:"ID,omitempty"`

	// Code: Code
	Code *string `json:"Code,omitempty"`

	// CostCenter: Cost Center linked to the project classification
	CostCenter *string `json:"CostCenter,omitempty"`

	// CostCenterDescription: Description of Costcenter
	CostCenterDescription *string `json:"CostCenterDescription,omitempty"`

	// CostUnit: Cost unit linked to the project classification
	CostUnit *string `json:"CostUnit,omitempty"`

	// CostUnitDescription: Description of Costunit
	CostUnitDescription *string `json:"CostUnitDescription,omitempty"`

	// Created: Creation date
	Created *types.Date `json:"Created,omitempty"`

	// Creator: User ID of creator
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Name of creator
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Description of the project classification
	Description *string `json:"Description,omitempty"`

	// Division: Division code
	Division *int `json:"Division,omitempty"`

	// DivisionName: Name of Division
	DivisionName *string `json:"DivisionName,omitempty"`

	// Modified: Last modified date
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: User ID of modifier
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Name of modifier
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// UseEmployeeCostCenter: Indicates whether to use employee cost center and cost unit
	UseEmployeeCostCenter *bool `json:"UseEmployeeCostCenter,omitempty"`
}

func (e *ProjectClassifications) GetPrimary() *types.GUID {
	return e.ID
}

func (s *ProjectClassificationsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "project/ProjectClassifications", method)
}

// List the ProjectClassifications entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ProjectClassificationsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*ProjectClassifications, error) {
	var entities []*ProjectClassifications
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectClassifications", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the ProjectClassifications entitiy in the provided division.
func (s *ProjectClassificationsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*ProjectClassifications, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectClassifications", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &ProjectClassifications{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty ProjectClassifications entity
func (s *ProjectClassificationsEndpoint) New() *ProjectClassifications {
	return &ProjectClassifications{}
}

// Create the ProjectClassifications entity in the provided division.
func (s *ProjectClassificationsEndpoint) Create(ctx context.Context, division int, entity *ProjectClassifications) (*ProjectClassifications, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectClassifications", division) // #nosec
	e := &ProjectClassifications{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the ProjectClassifications entity in the provided division.
func (s *ProjectClassificationsEndpoint) Update(ctx context.Context, division int, entity *ProjectClassifications) (*ProjectClassifications, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectClassifications", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &ProjectClassifications{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the ProjectClassifications entity in the provided division.
func (s *ProjectClassificationsEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectClassifications", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
