// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package sales

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/stack11/go-exactonline/api"
	"github.com/stack11/go-exactonline/types"
)

// SalesChannelsEndpoint is responsible for communicating with
// the SalesChannels endpoint of the Sales service.
type SalesChannelsEndpoint service

// SalesChannels:
// Service: Sales
// Entity: SalesChannels
// URL: /api/v1/{division}/sales/SalesChannels
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesSalesChannels
type SalesChannels struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Primary key
	ID *types.GUID `json:"ID,omitempty"`

	// Active: Active
	Active *bool `json:"Active,omitempty"`

	// Code: Code of the sales channel
	Code *string `json:"Code,omitempty"`

	// Created: Creation date
	Created *types.Date `json:"Created,omitempty"`

	// Creator: User ID of creator
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Name of creator
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Description of sales channel
	Description *string `json:"Description,omitempty"`

	// Division: Division code
	Division *int `json:"Division,omitempty"`

	// Modified: Last modified date
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: User ID of modifier
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Name of modifier
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Notes
	Notes *string `json:"Notes,omitempty"`
}

func (e *SalesChannels) GetPrimary() *types.GUID {
	return e.ID
}

func (s *SalesChannelsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "sales/SalesChannels", method)
}

// List the SalesChannels entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SalesChannelsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*SalesChannels, error) {
	var entities []*SalesChannels
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sales/SalesChannels", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the SalesChannels entitiy in the provided division.
func (s *SalesChannelsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*SalesChannels, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sales/SalesChannels", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &SalesChannels{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty SalesChannels entity
func (s *SalesChannelsEndpoint) New() *SalesChannels {
	return &SalesChannels{}
}

// Create the SalesChannels entity in the provided division.
func (s *SalesChannelsEndpoint) Create(ctx context.Context, division int, entity *SalesChannels) (*SalesChannels, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sales/SalesChannels", division) // #nosec
	e := &SalesChannels{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the SalesChannels entity in the provided division.
func (s *SalesChannelsEndpoint) Update(ctx context.Context, division int, entity *SalesChannels) (*SalesChannels, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sales/SalesChannels", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &SalesChannels{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the SalesChannels entity in the provided division.
func (s *SalesChannelsEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sales/SalesChannels", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
