// Copyright 2022 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package sales

import (
	"context"

	"github.com/stack11/go-exactonline/api"
	"github.com/stack11/go-exactonline/types"
)

// SalesPriceListsEndpoint is responsible for communicating with
// the SalesPriceLists endpoint of the Sales service.
type SalesPriceListsEndpoint service

// SalesPriceLists:
// Service: Sales
// Entity: SalesPriceLists
// URL: /api/v1/{division}/sales/SalesPriceLists
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesSalesPriceLists
type SalesPriceLists struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Primary key. Price list ID
	ID *types.GUID `json:"ID,omitempty"`

	// Code: Price list code
	Code *string `json:"Code,omitempty"`

	// Created: Creation date
	Created *types.Date `json:"Created,omitempty"`

	// Creator: User ID of creator
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Name of creator
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Currency: All prices in the price list are stored in this currency
	Currency *string `json:"Currency,omitempty"`

	// Description: Price list description
	Description *string `json:"Description,omitempty"`

	// Division: Division code
	Division *int `json:"Division,omitempty"`

	// Entity: Indicates the entity (1 - Item, 2 - Item group) on which this price list is based
	Entity *int `json:"Entity,omitempty"`

	// Modified: Last modified date
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: User ID of modifier
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Name of modifier
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Explanation or extra information can be stored in the notes
	Notes *string `json:"Notes,omitempty"`

	// Type: Indicates the type (1 - Customer, 2 - Standard) on which this price list applies
	Type *int `json:"Type,omitempty"`
}

func (e *SalesPriceLists) GetPrimary() *types.GUID {
	return e.ID
}

func (s *SalesPriceListsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "sales/SalesPriceLists", method)
}

// List the SalesPriceLists entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SalesPriceListsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*SalesPriceLists, error) {
	var entities []*SalesPriceLists
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sales/SalesPriceLists", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the SalesPriceLists entitiy in the provided division.
func (s *SalesPriceListsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*SalesPriceLists, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sales/SalesPriceLists", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &SalesPriceLists{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
